{% set name = "liquidhandling" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
 
source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - jsonref
    - jsonschema
    - pip
    - pytest
    - python
  run:
    - jsonref
    - jsonschema
    - pytest
    - python

test:
  imports:
    - liquidhandling

about:
  home: "http://github.com/luckierdodge/liquidhandling"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A python library developed to allow programmatic control of the Hudson Robotics systems installed in Argonne National Laboratory's Secure BIO Lab."
  doc_url: 
  dev_url: 
