{% set name = "liquidhandling" %}
{% set version = "0.1.18" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
 
source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - jsonref
    - jsonschema
    - pip
    - pytest
    - python
    - pandas
    - path
    - openpyxl
    - mysql-connector-python
    - zmq
  run:
    - jsonref
    - jsonschema
    - pytest
    - python
    - pandas
    - path
    - openpyxl
    - mysql-connector-python
    - zmq

test:
  imports:
    - liquidhandling

about:
  home: "http://github.com/luckierdodge/liquidhandling"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A python library developed to allow programmatic control of the Hudson Robotics systems installed in Argonne National Laboratory's Secure BIO Lab."
  doc_url: 
  dev_url: 
